# Generated by Django 5.2.7 on 2025-11-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_change_book', 'Can change book'), ('can_delete_book', 'Can delete book'), ('can_view', 'Can view books'), ('can_create', 'Can create books'), ('can_edit', 'Can edit books'), ('can_delete', 'Can delete books')]},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'permissions': [('can_view_library', 'Can view library'), ('can_create_library', 'Can create library'), ('can_edit_library', 'Can edit library'), ('can_delete_library', 'Can delete library')], 'verbose_name_plural': 'Libraries'},
        ),
    ]
