# Generated by Django 5.2.7 on 2025-11-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_change_book', 'Can change book'), ('can_delete_book', 'Can delete book')]},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_manage_roles', 'Can manage user roles')]},
        ),
    ]
