# Generated by Django 5.2.8 on 2025-12-11 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read', 'created_at'], name='notificatio_recipie_9c8dcc_idx'),
        ),
    ]
